#for configuration start: roslaunch tod_input_devices tod_input_devices.launch ConfigMode:=true
Type : "Usb" #Usb or Virtual

ButtonConfig:
  "IndicatorLeft": 11                 #LB
  "IndicatorRight": 3                 #RB
  "FlashLight": 9                     #Y
  "FrontLight": 21                    #X
  "Honk": 25                          #B
  "IncreaseSpeed": 23                 #bottom left wheel clockwise
  "DecreaseSpeed": 22                 #bottom left wheel counter clockwise
  "IncreaseGear": 4                   #Right pedal
  "DecreaseGear": 5                   #Left pedal

AxisConfig:
  "Steering": 0
  "Throttle": 2
  "Brake": 5

InputDeviceHasSeparateBrakingAxis: true #If False: AxisRange/Brake is ignored (see below)

InvertAxis:
  "Steering": true 
  "Throttle": true
  "Brake": true

Correction: "11,\
  1,255,32767,32767,18000,18000,\
  1,0,0,0,0,0,\
  1,255,32767,32767,18000,18000,\
  1,0,0,0,0,0,\
  1,0,0,0,0,0,\
  1,255,32767,32767,18000,18000,\
  1,0,0,0,0,0,\
  1,0,0,0,0,0,\
  1,0,0,0,0,0,\
  1,0,0,0,0,0,\
  1,0,0,0,0,0"
