# not for open source
#for configuration start: roslaunch tod_input_devices tod_input_devices.launch ConfigMode:=true
Type: "Usb" #Usb oder Virtual oder Senso

ButtonConfig:
  "IndicatorLeft": 85 
  "IndicatorRight": 79
  "FlashLight": 70
  "FrontLight": 76
  "Honk": 32
  "IncreaseSpeed": 87
  "DecreaseSpeed": 83
  "IncreaseGear": 84
  "DecreaseGear": 71

AxisConfig:
  "Steering": 0
  "Throttle": 1
  "Brake": 2

InputDeviceHasSeparateBrakingAxis: false #If False: AxisRange/Brake is ignored (see below)

InvertAxis:
  "Steering": true 
  "Throttle": true
  "Brake": true

