#for configuration start: roslaunch tod_input_devices tod_input_devices.launch ConfigMode:=true
Type : "Usb" #Usb or Virtual

ButtonConfig:
  "IndicatorLeft": 6                # Back (Left Thumb)
  "IndicatorRight": 7               # Start (Right Thumb)
  "FlashLight": 8                   # Green XBOX (Right Thumb)
  "FrontLight": 3                   # Y (Right Thumb)
  "Honk": 0                         # A (Right Thumb)
  "IncreaseSpeed": 5                # RB (Right Index Finger)
  "DecreaseSpeed": 4                # LB (Left Index Finger)
  "IncreaseGear": 1                 # B (Right Thumb)
  "DecreaseGear": 2                 # X (Right Thumb)

AxisConfig:
  "Steering": 0                     # Left Knob (Left Thumb)
  "Throttle": 5                     # RT Lever (Right Index Finger)
  "Brake": 2                        # LT Lever (Left Index Finger)

InputDeviceHasSeparateBrakingAxis: true #If False: AxisRange/Brake is ignored (see below)

InvertAxis:
  "Steering": true 
  "Throttle": false
  "Brake": false
